### ISSUE TITLE
can't render contextMenu with this component

### ISSUE THREAD

**Issue by guirenpei** [fkhadra/react-contexify#100]
background: antd
when i use react-contexify in antd with Tree Component, i had bugs
```react
<TreeNode title={<ContextMenuProvider id='menu_id' data-key={item.key}><span>{item.title}</span></ContextMenuProvider>} key={item.key} dataRef={item}>
          {this.renderTreeNodes(item.children)}
        </TreeNode>
```
```react
<ContextMenu id='menu_id'>
          <Item onClick={onContextMenuClick}>Lorem</Item>
          <Item onClick={onContextMenuClick}>Ipsum</Item>
          <Separator />
          <Item disabled>Dolor</Item>
          <Separator />
          <Submenu label="Foobar">
            <Item onClick={onContextMenuClick}>Foo</Item>
            <Item onClick={onContextMenuClick}>Bar</Item>
          </Submenu>
        </ContextMenu>
```
result:
`Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
Check the render method of CContextMenu.`

**Comment by jkeruzec** [comment]
Same error here, I look for some solutions wihtout success. 

Could you provide some details, or new way to implement context menu ?

**Comment by jkeruzec** [comment]
I did the migration with success, some main keys are to choose new declarations :

`import { Menu, Item, contextMenu } from 'react-contexify';`

And to follow the steps here : 
# Migrate from v3

- `ContextMenu` has been renamed to `Menu`
- `ContextMenuProvider` has been renamed to `MenuProvider`
- The `onClick` callback signature has been simplified. The `data` and the `ref` are merged to props.

```js
// Old signature
({ event, ref, data, dataFromProvider }) => void;

// New one
({ event, props }) => void;
```

- The `MenuProvider` is limited a new api has been introduced to give more control. Please check the usage [here](/you-dont-need-the-menu-provider). The `contextMenu` helper
is a game changer.

**Comment by fkhadra** [comment]
Hello,

Sorry for the late reply. @jkeruzec thank you for sharing the solution.
