### ISSUE TITLE
Provide a way to do some action when user event is launch (oncontextmenu)

### ISSUE THREAD

**Issue by jkeruzec** [fkhadra/react-contexify#101]
I'd like to trigger an action before context menu is show to the user.

Is there a way to provide like a callback on the event ?

For instance : 
User click context menu provider with contextmenu event => I do some actions => menu is displayed to user.

**Comment by fkhadra** [comment]
Hello @jkeruzec,

You can use the `contextMenu` helper instead of the `Provider` as show [here](https://fkhadra.github.io/react-contexify/you-dont-need-the-menu-provider)   

Is it what you are looking for ?

**Comment by jkeruzec** [comment]
Hi @fkhadra 

Can you provide src code for this example please ?

**Comment by fkhadra** [comment]
There you go
[![Edit vq5n8vv2x3](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vq5n8vv2x3)

**Comment by jkeruzec** [comment]
Thanks, code is only available in version 4.0 ?

**Comment by fkhadra** [comment]
Yes I introduced the `contextMenu` api with the v4

**Comment by jkeruzec** [comment]
Great !! I migrate to V4.0.1 and go for controlled context menu. 
I can now trigger selection on my tree node using react-sortable-tree while displaying context menu.

Thank you !

**Comment by jkeruzec** [comment]
@fkhadra Maybe the canvas square thing on the example might be a little disturbing for new comers. A simple text may be easily readable and straightforward :)
