### ISSUE TITLE
Would it be possible to add identifiers to Items.

### ISSUE THREAD

**Issue by crhistianramirez** [fkhadra/react-contexify#103]
We are doing some integration testing and it would be ideal if we could set a `data-test-id` attribute on the Item elements so that our tests can target the elements correctly, or an ID.

We're using `className` at the moment but we'd rather it not be coupled to that in case a designer comes in and wants to update it.

**Comment by fkhadra** [comment]
Hello @crhistianramirez,

Sounds like a good idea to accept id or a data attribute. Do you want to work on it ? The change is trivial.

**Comment by fkhadra** [comment]
This is solved in v5. Every component accepts any HTML Attribute. The library has been tested using cypress. You can have a look at the example folder in the repo.
