### ISSUE TITLE
Regression: Nested MenuProviders no longer works

### ISSUE THREAD

**Issue by Phault** [fkhadra/react-contexify#104]
The issue from #67 has re-emerged. Here's an updated sandbox.
https://codesandbox.io/s/54vkk41wxl

Seems like the fix was lost in the transition to TypeScript.

**Comment by amitassaraf** [comment]
@Phault Any progress on this? I tried manually applying the fix though it seemed to not help.

**Comment by Phault** [comment]
@amitassaraf 
Yeah, the fix worked for me. My pull request didn't include an updated build though. So you'll have to build react-contexify yourself with the fix, if you didn't already.

**Comment by fkhadra** [comment]
Hey,

The fix is live. Thanks for the PR
