### ISSUE TITLE
Filter Drop-Down Lookup Options

### ISSUE THREAD

**Issue by mindey** [fkhadra/react-contexify#106]
Can we have the text input field at the top of the context-menu, which allows to filter the drop-down select options?

It would be useful, when the number of options in the context-menu is large.

**Comment by fkhadra** [comment]
This is something that could be implemented using the v5 and custom position. Have a look at [this](https://fkhadra.github.io/react-contexify/set-a-custom-position/#recreate-the-dropdown-step-by-step)
