### ISSUE TITLE
Check disabled in Item.render()

### ISSUE THREAD

**Issue by marcusbrose** [fkhadra/react-contexify#108]
Caching the `disabled` value to a variable on init / click is not a good idea in my opinion. Just check it in the `render()` method and let React decide what to update. 

In the current implementation Items do not update when the `disabled`-prop is changing while the context menu is open. Any logic should be outside the component and be injected. 
https://github.com/fkhadra/react-contexify/blob/0cddfd906fc8549699e5bd55678e906d8f8bfe4e/src/components/Item.tsx#L56-L78

**Comment by trannamquan** [comment]
Same issue found here. The prop passed to disabled function did not update when changing while the context menu is open.

**Comment by DusterTheFirst** [comment]
bump. This is an issue with all computed values for items. They only update when the context menu is hidden and then recreated. This is the only workaround i can find.

```ts
contextMenu.hideAll();
setTimeout(() => contextMenu.show({
    event,
    id,
    props: selection
}), 1);
```

**Comment by fkhadra** [comment]
Starting v5 `disabled` is not cached anymore.
