### ISSUE TITLE
Right click behaviour

### ISSUE THREAD

**Issue by brezetsky** [fkhadra/react-contexify#11]
Default context-menu shown when you clicked right click menu while menu is opened.
<img width="806" alt="screen shot 2017-05-18 at 11 17 28 am" src="https://cloud.githubusercontent.com/assets/24649701/26195319/ad80f894-3bbb-11e7-89b6-7ce699eac831.png">

**Comment by fkhadra** [comment]
@brezetsky it will be fixed in the release

**Comment by brezetsky** [comment]
Thanks. When will be next release?

**Comment by fkhadra** [comment]
@brezetsky. This week, tonight or tomorrow. I have to end the documentation.
That version will be not backward compatible. I hate to do that but I had too.
I'll warn you as soon as I release it

**Comment by brezetsky** [comment]
Great, thank you!
