### ISSUE TITLE
CTRL+Left Click

### ISSUE THREAD

**Issue by torchsmith** [fkhadra/react-contexify#111]
When ever I use control+left click (using a macbook trackpad), the menu appears, but instantly disappears.

Wondering if I could get some help with the problem, or if there is a solution.

**Comment by torchsmith** [comment]
Turns out that the reason for it disappearing is that when pressing `CTRL+Left Click`, it triggers context menu, but when letting go of the `Left Mouse Button` it triggers the `Click` event which then closes the context menu.

**Comment by torchsmith** [comment]
It looks like it works correctly in the example project. I'm going to take a closer look into the scenario I have.

**Comment by torchsmith** [comment]
Found the problem, not related to the source code of this repo.

**Comment by leefsmp** [comment]
I have the same behavior, @torchsmith do you mind sharing what was the issue on your side? Thanks!
