### ISSUE TITLE
Receiving "Function components cannot be given refs." warning

### ISSUE THREAD

**Issue by jktravis** [fkhadra/react-contexify#113]
I'm changing a component that was being wrapped by `MenuProvider` to a function component, and am getting this warning.

> Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

It still seems to work, however. 

I didn't see an existing issue for it.

**Comment by YiRancn** [comment]
dont direct contain componet,    must contain Native HTML elements

**Comment by ronaklalwaniii** [comment]
Hello, I am also facing the same warning. What's the fix?

**Comment by KfirAlfa** [comment]
Any news about that? I am facing the same problem.

**Comment by jktravis** [comment]
I think I either just implemented the [forwardRef](https://reactjs.org/docs/forwarding-refs.html) on my non-standard component or wrapped it in a <div> or something.

**Comment by jmca** [comment]
You could use a fragment in a pinch, that's what I'm currently doing: 
```
<MenuProvider />
    <>
        <SomeFunctionalComp />
    </>
</MenuProvider>
```

**Comment by renato-bohler** [comment]
Apparently setting the `storeRef` prop to `false` also removes the warning.

```JavaScript
// No warnings :)
<MenuProvider id={event.model.options.id} storeRef={false}>
  <Widget engine={this.engine} model={event.model} />
</MenuProvider>
```
---
```JavaScript
// Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
<MenuProvider id={event.model.options.id}>
  <Widget engine={this.engine} model={event.model} />
</MenuProvider>
```

**Comment by fkhadra** [comment]
`MenuProvider` has been dropped starting v5 due to the lack of flexibility.
