### ISSUE TITLE
Cannot read property 'offsetWidth' of undefined

### ISSUE THREAD

**Issue by KthProg** [fkhadra/react-contexify#115]
Apparently this will happen when you don't make the id unique for each menu. A more helpful error would be cool.

**Comment by KirillSuhodolov** [comment]
I got this error even one menu item and provider at app

**Comment by KevinDenys** [comment]
I also can't get it working

**Comment by Winangel** [comment]
same issue here, don't know why but the setRef is never called in the Menu item

**Comment by rikinshah23** [comment]
@Winangel I could not understand your solution. could you please paste a sample here?
I am having the same problem. I have only one menu on this page and id is unique to Menu and MenuProvider

**Comment by Winangel** [comment]
> @Winangel I could not understand your solution. could you please paste a sample here?
> 
> I am having the same problem. I have only one menu on this page and id is unique to Menu and MenuProvider
> 
> 

my problem was that I was using the Menu provider method and the contextMenu method alongside. The solution was to use only one method in the whole application (contextMenu in my case).

**Comment by Hasan330** [comment]
Can anyone provide a sample code snippet please? Can't seem to work for me either

**Comment by zlanich** [comment]
This is happening to me as well with either `<MenuProvider />` or `contextMenu`. I haven't yet found a pattern. It just doesn't seem to work for me yet. I will update this if I figure it out.

**Comment by fkhadra** [comment]
Hey,

`MenuProvider` has been dropped starting v5 due to the lack of flexibility. I'll close this issue. Feel free to reopen the issue if it's popup again with the new implementation
