### ISSUE TITLE
One context per <tr></tr>

### ISSUE THREAD

**Issue by xaoc2nd** [fkhadra/react-contexify#118]
Hello,

Your components are realy useful but I can't manage to use it with a table for each row.

I can use it with the whole table and right click everywhere on the table but what I want to do is to click on a row and printing a different context depending on the row.

Is it possible?

Thanks a lot

**Comment by dpren** [comment]
Yes please. Currently, I believe the only way is to conditionally id a separate Menu for every condition, or do some refs hack.

Could we have `<Menu/>` expose a render prop like this?

```jsx
contextMenu.show({
   props: {
      foo: true,
   }
})

<Menu render={props => (
   <Item >{props.foo}</Item>
)}/>
```

**Comment by fkhadra** [comment]
If you want to render a different Menu based on the selected row, I would suggest that you render a Menu with all the Items and hide the unnecessary items based on a boolean predicate.

```jsx
<Menu>
<Item hidden={}> Item 1</Item>

</Menu>
```
