### ISSUE TITLE
Hundreds of <div></div> created in DOM when menu used

### ISSUE THREAD

**Issue by perry-mitchell** [fkhadra/react-contexify#119]
For some reason after adding a new menu, I see hundreds of empty divs in the DOM:

![image](https://user-images.githubusercontent.com/3869469/60648252-37a67300-9e48-11e9-98ee-25b3c35748b7.png)

This is a performance concern - the divs should not be present. I am creating a menu per item in a table, so iteration here is creating a lot of menu instances.

Not sure if the div has something to do with portals in react, but if I delete a div and then unmount the menus and their parent components, I see the following:

![image](https://user-images.githubusercontent.com/3869469/60648386-80f6c280-9e48-11e9-8a6a-4fece680fa9b.png)

**Comment by fkhadra** [comment]
Hello @perry-mitchell,

Thanks for reporting the issue. May I ask you to create a codesanbox with the issue ?

Thanks

**Comment by fkhadra** [comment]
Starting v5, this behavior won't occur anymore
