### ISSUE TITLE
Unpossible to use React condition

### ISSUE THREAD

**Issue by brezetsky** [fkhadra/react-contexify#12]
next structure doesn't work in case of condition is false
`{condition && <Separator/> && <Item label="label" disabled/>}`

**Comment by fkhadra** [comment]
Can you give more details? I don't get the point here...

**Comment by brezetsky** [comment]
Updated. Added like a code this time. Please, look on it one more time.

**Comment by fkhadra** [comment]
if the condition is false with the following  structure `{condition && <Separator/> && <Item label="label" disabled/>}`  it will always be false.

If you want to render a separator or an item depending on the condition a ternary is what you are looking for.
`condition ?  <Separator/> :  <Item label="label" disabled/>`


![image](https://cloud.githubusercontent.com/assets/5574267/26200872/a480a374-3bd0-11e7-9dd7-938bc205d2cb.png)

This has nothing to do with the component, it's pure javascript in that case. 

If I miss something please tell me.

**Comment by brezetsky** [comment]
Yes. Your code works. But I would like just if condition. And it something what I have done.
But if condition is true, I would like to add item to menu and without else.

**Comment by brezetsky** [comment]
Like **Inline If with Logical && Operator** here https://facebook.github.io/react/docs/conditional-rendering.html

**Comment by fkhadra** [comment]
Ok I start to understand now 😁 . If your condition is true you want to render both the <Separator /> and <Item /> ?

**Comment by fkhadra** [comment]
In that case : `{condition && <Separator/> && <Item label="label" disabled/>}` if the condition is true only
`<Item label="label" disabled/>`  will be rendered

**Comment by brezetsky** [comment]
Can not agree with you. If condition is true both of them will  rendered and it works perfectly.
But problem if condition return false. 
<img width="609" alt="screen shot 2017-05-18 at 2 26 45 pm" src="https://cloud.githubusercontent.com/assets/24649701/26202001/0a8f05a2-3bd6-11e7-9576-153f08493aa9.png">

**Comment by fkhadra** [comment]
If i do the following : `{true && <h1>foo</h1> && <div>bar</div> }`  only bar is rendered.

Snippet here : [codepen](http://codepen.io/sniphpet/pen/Wjgqre).

Can you provide a pen ?

**Comment by brezetsky** [comment]
Yes. You are right about true condition
What about false conditions. It produce a error. And it was my question originally

**Comment by fkhadra** [comment]
What you need to do is : 
` {false && (<div><h1>foo</h1><div>bar</div></div>)}`  As you can see you need to wrap the element.
` {false && (<h1>foo</h1><div>bar</div>)}` . Without the div it won't work.

So in your case, it will be easier if you do because you can't group the separator and the item :

`` {condition && <Separator />}``
`` {condition && <item />}``

snippet : [codepen](http://codepen.io/sniphpet/pen/Wjgqre)

**Comment by brezetsky** [comment]
That is not a problem. Problem exists in that moment when condition is false
Then {condition && <item />} returns error 
<img width="806" alt="screen shot 2017-05-18 at 11 17 28 am" src="https://cloud.githubusercontent.com/assets/24649701/26206601/953c1f46-3be5-11e7-8866-4e52f2e50aec.png">

**Comment by brezetsky** [comment]
And my expectations is not see separator it item if conditions will be false, without any error

**Comment by fkhadra** [comment]
Can you send me the full snippet so I can reproduce the issue ?

**Comment by brezetsky** [comment]
Sorry for late answer. Not sure how I can add this plugin to codepen. At least, code for reproducing you can find below.






`        <ContextMenuProvider id={'context_menu' }>
          Right click
        </ContextMenuProvider>
        <ContextMenu id={'context_menu' }>
          {enabled ?
            (<Item label="Item 1"/>) :
            (<Item label="Item 1" disabled />)
          }

          {false && <Item label="Item 2 will produce a error" />}
        </ContextMenu>`

**Comment by brezetsky** [comment]
If you can explain me how to add library to codepen -  I will add a snippet

**Comment by fkhadra** [comment]
@brezetsky the code is enough thanks. I'll check it when I'm home.

**Comment by fkhadra** [comment]
Hey, in the next release this `{false && <Item label="Item 2 will produce a error" />}`  will work without any issue.I'm almost done

**Comment by brezetsky** [comment]
Thanks.
Waiting for new release 👍

**Comment by fkhadra** [comment]
@brezetsky new release published. I still need to update the demo

**Comment by brezetsky** [comment]
@fkhadra problem still appear

**Comment by fkhadra** [comment]
@brezetsky you updated to the last version ? 
I'll check when I'm home but it should work. I even included the case inside my test.
But i'll check asap.

**Comment by brezetsky** [comment]
Sure.
This works for me https://github.com/fkhadra/react-contexify/issues/11

**Comment by fkhadra** [comment]
@brezetsky new fix inc is few minutes. My test case was bad !

**Comment by brezetsky** [comment]
Thanks.
