### ISSUE TITLE
MenuProvider data not passed to Submenu

### ISSUE THREAD

**Issue by Kinark** [fkhadra/react-contexify#122]
I don't know if this is a duplicate of #97, but I can't have access to the `MenuProvider` `data` when I click on a `Submenu`.

I hope it's not a duplicate.

**Comment by fkhadra** [comment]
Hello @Kinark,

Do you mind to create a codesandbox with the issue ?

Thanks

**Comment by humbkr** [comment]
Maybe related to #132

**Comment by fkhadra** [comment]
Hey,

Starting v5, `MenuProvider` has been dropped
