### ISSUE TITLE
No type definitions (.d.ts files)

### ISSUE THREAD

**Issue by jumpinjackie** [fkhadra/react-contexify#129]
Your npm package does not have any `.d.ts` files even though your `tsconfig.json` has [declaration: true](https://github.com/fkhadra/react-contexify/blob/master/tsconfig.json#L13)

It means typescript projects consuming this package have no "intellisense"

**Comment by jumpinjackie** [comment]
Ok, I installed the wrong package. I installed react-contextify (note the extra 't'), which is this repo: https://github.com/galkinrost/react-contextify

Other might get confused like I did, might want to point this out in the readme somewhere.

**Comment by ekilah** [comment]
this definitely just got me 🙈 thanks for posting.
