### ISSUE TITLE
how to pass relative data to menu when an item is clicked?

### ISSUE THREAD

**Issue by MonkeyJumps** [fkhadra/react-contexify#135]
I have a list of items that i want to right click on and when a user selects an item from the context menu I need to know from which element that request was triggered. I have the following but I am currently stuck. Can someone provide an example of passing relative data up to the menu when the user right clicks on an element? Do i have to wrap a MenuProvider around each element and if so will that performant with a lot of data?

```jsx
      <React.Fragment>
        <MenuProvider id="menu_id" className={selectedThumbnailView} render={{ CustomComponent, ...this.props }}>
          {pages.map(this.createThumbnailTemplate)}
        </MenuProvider>
        <MyMenu />
      </React.Fragment>
```

**Comment by bytrix** [comment]
same problem, need help!!!!

**Comment by bytrix** [comment]
my way is to pass onContextMenu props to MenuProvider
`
                    {this.props.taskList.items && this.props.taskList.items.map(item => (
                        <MenuProvider id='task_menu' onContextMenu={e => {
                            this.setState({
                                currentItem: item
                            })
                        }}>
                            <Menu.Item onClick={() => this.props.onItemClick(item)}>
                                {item.taskName}
                            </Menu.Item>
                        </MenuProvider>
                    ))}
`

**Comment by fkhadra** [comment]
Hey,

The v5 has been released and a new doc is available. I suggest that you look at [this](https://fkhadra.github.io/react-contexify/handle-item-click)
