### ISSUE TITLE
Stop Propagation on item click

### ISSUE THREAD

**Issue by diegodebonis** [fkhadra/react-contexify#136]
Hi im trying to do something like this on a table
```
 { menuIndex && menuOptions && <Menu id={`menu_id_${row.values[menuIndex]}`}>
    {menuOptions.map((item, j) => (
   <Item
     onClick={({event}) => {event.stopPropagation();event.preventDefault()}}
     key={j}>
    {item.label}
  </Item>
))}
```
But everytime i click the option the `<tr>` tag fires the click event, is there any way to prevent this?

**Comment by doanhuyc** [comment]
i have the same issue here, anyone please help.

**Comment by fkhadra** [comment]
This feature will land in v5. You can follow the PR [here](https://github.com/fkhadra/react-contexify/pull/152). I'm reworking the doc right now. I'll do my best to publish this new version this week.

**Comment by fkhadra** [comment]
Hey,
This is possible in v5. This is documented [here](https://fkhadra.github.io/react-contexify/prevent-menu-from-closing)
