### ISSUE TITLE
Enable mounting in Iframe instead of document per default

### ISSUE THREAD

**Issue by fabiobaser** [fkhadra/react-contexify#138]
I am working on a react app that is getting rendered inside of an Iframe. (Sounds stupid but it has to be like that). Sadly the ContextMenu always gets appended to the document.body. It would be nice to be able to pass a HTMLNode as a prop where the ContextMenu gets mounted. Semantic-UI-React is using this approach. https://react.semantic-ui.com/modules/modal/

I already bodged a solution for my use-case. If nobody has the time, I could prepare a PR.

**Comment by Suibs** [comment]
On the same boat, did you manage to work around the issue?

**Comment by fabiobaser** [comment]
@Suibs I've included the module as a local module and rewritten the code so the Menu is mounted on a HTMLNode that I referenced on a window variable. I mean it works.

**Comment by Suibs** [comment]
@fabiobaser that's what I was thinking of doing too. Smart choice!

**Comment by fkhadra** [comment]
Hey,
With the v5 this is possible. Have a look at [here](https://fkhadra.github.io/react-contexify/mount-menu-at-specific-place)
