### ISSUE TITLE
Incorrect event.clientX in iFrame

### ISSUE THREAD

**Issue by chuikoffru** [fkhadra/react-contexify#141]
Hello everyone!

Faced with trouble. When I click on `MenuProvider`, which located at iframe, then the context menu shows far from my cursor.

![Screenshot 2020-06-12 at 15 50 53](https://user-images.githubusercontent.com/8284619/84463188-10495e80-acc5-11ea-929e-82f5d917d9e4.png)

`event.clientX` shows `250`, but my cursor was at the center of the page. 
The right side is an `iframe`.

**Comment by shivampip** [comment]
Hi @chuikoffru , did you find a way to make it work properly in an iframe?

**Comment by fkhadra** [comment]
Hello guys,
The v5 will be available soon. I'm currently writing the documentation. The beta package is already published to npm. The v5  let you specify a custom dom node to mount the menu. This will be helpful in such case

**Comment by fkhadra** [comment]
Hey, v5 has been released. You can solve your issue using react portal. THis is documented [here](https://fkhadra.github.io/react-contexify/mount-menu-at-specific-place)
