### ISSUE TITLE
Long click / click and hold

### ISSUE THREAD

**Issue by oyeanuj** [fkhadra/react-contexify#142]
Hi @fkhadra, thank you for creating this excellent library! My use-case is to have a context menu show up on long click / click and hold (and not just a simple click). Is it possible to use /modify this library to do that, similar to the `onClick` mechanism?

**Comment by fkhadra** [comment]
Hey @oyeanuj ,

Thanks for your feedback and sorry for the late reply.

The library gives you the freedom to display the Menu whenever you like.


```jsx
import { useContextMenu } from 'react-contexify'

function App(){
  const { show } = useContextMenu({ id: 'menuId' });
  cons timeoutId = useRef(null);

  function longClick(e){
    // display menu after 3 sec
    timeoutId.current = setTimeout(() => show(e), 3000)
  }

  function clear(){
    clearTimeout(timeoutId.current)
  }

  return <div onMouseDown={longClick} onMouseUp={clear}>long click me</div>
}


```
