### ISSUE TITLE
Is there custom theme support?

### ISSUE THREAD

**Issue by exapsy** [fkhadra/react-contexify#153]
Is there a way to add custom theming? The docs do not clarify the if's and how's. I expect it to be possible if done via overriding CSS rules though, it's just not clarified if that's how you're supposed to theme it in the docs.

**Comment by exapsy** [comment]
I took a look at the code, and there's `className` as prop in `Menu`. But probably there should be an example, with the classes used and how exactly you can customize each element.

**Comment by fkhadra** [comment]
Hey @exapsy,

You can have a look at the [doc]. I've just released the v5.
