### ISSUE TITLE
Use custom menu

### ISSUE THREAD

**Issue by nextglabs** [fkhadra/react-contexify#154]
Is there a way to use a custom menu (for instance MaterialUI `<List />` or `<Menu />` component) instead of the default <Menu /> shipped with `react-contexify`?

**Comment by fkhadra** [comment]
Hey @nextglabs ,

This is not possible so far. A new version has been released today, the doc has been updated as well. There is a whole section on styling [here](https://fkhadra.github.io/react-contexify/how-to-style)
