### ISSUE TITLE
Event not bound

### ISSUE THREAD

**Issue by Bilb** [fkhadra/react-contexify#155]
Hi
I found a few issues related to this error, but mine might be different. If not, my apologies.

My app is a chat app with a `header` of the selected conversation. When the selected conversation is switched, the header is updated with new props. One of them is the conversation id.
This `header` has a `Menu` available (`onClick`, but same issue with the `onContextMenu`) and this menu id basically `header-${conversation-id}`.

Looking at the code, I think I have this issue because we only subscribe to menu events on the `componentDidMount()` method. https://github.com/fkhadra/react-contexify/blob/master/src/components/Menu.tsx#L91

Shouldn't we unsubscribe and resubscribe on `componentDidUpdate()` too?
I double checked, and if I just use a static id for the header menu, everything works as expected.

I understand this might not have happen to you already, and I can just use the same id for my header in  the end, but I guess it's an easy fix and it makes sense to me.

What do you think? I can get a PR if you approve.

**Comment by fkhadra** [comment]
Hey @Bilb ,

Can you upgrade to the latest version and check if you still encounter the issue?

**The latest version includes some breaking changes**

**Comment by Bilb** [comment]
Hey @fkhadra there is no way to NOT use hooks with the latest release 5.0.0?

**Comment by fkhadra** [comment]
Hey @Bilb ,

You can use the `contextMenu` object. https://fkhadra.github.io/react-contexify/trigger-the-menu-outside-of-react-compoent

**Comment by Bilb** [comment]
@fkhadra thanks it's working. I just have an issue with the placement of the menu in a scrollable container with some overflow.
The menu position is correct when I am on the middle of the scrollable container and there are some hidden elements on top and bottom, but if I try to show it white somewhere the top or the bottom, the menu is several elements above/below the clicked element

**Comment by Bilb** [comment]
have a look here: https://imgur.com/a/F19dnKO do you want me to open an issue for that?

**Comment by fkhadra** [comment]
Yes please. Also if you can share the repo with the issue or reproduce the issue on codesanbox it would be awesome

**Comment by Bilb** [comment]
I fixed it,
the issue was that my container was absolutely positioned, and the fixed position of the menu (0,0) was relative to that container offset.
I fixed it using a portal to some of the root element of the page.
I don't quite get why it was not happening with v4.1.1 though, but all good now !

Thanks a lot for your work

**Comment by Bilb** [comment]
And just so it's noted, I did not managed to reproduce the issue I encouter on this issue (event not bound)
