### ISSUE TITLE
Context menu disappear after unpressing right button  in Firefox

### ISSUE THREAD

**Issue by brezetsky** [fkhadra/react-contexify#16]
Right button press and hold - menu appears.
Right button unpress - menu disappears(for Mozilla).

Works for Chrome.

**Comment by fkhadra** [comment]
I just noticed that firefox trigger a click event on right click up ...

**Comment by fkhadra** [comment]
@brezetsky fixed. I need to test on safari but I don't have a mac at work

**Comment by brezetsky** [comment]
Thanks.
Works for me in safari too.

**Comment by C3PablO** [comment]
this still not working in Safari if you right-click using ctrl + trackpad-click. I can reproduce it on the demo page

**Comment by C3PablO** [comment]
Is the same issue that Firefox had before but in this case e.button === 0 instead 2 so it doesn't enter the conditional to not close the menu
