### ISSUE TITLE
how to position the menu to the left from the click point

### ISSUE THREAD

**Issue by NemanjaS2P** [fkhadra/react-contexify#160]
When i click on my button the context menu show up on the right side where the click was. How can i change the position of the menu and put it on the left side. What property do i change to achieve this?

How it is now:
 
<img width="290" alt="Brez naslova" src="https://user-images.githubusercontent.com/62139963/102907896-f7d9ae00-4476-11eb-922c-d6c67e05f1f6.png">

How i want it to look like:
<img width="269" alt="Brez naslova2" src="https://user-images.githubusercontent.com/62139963/102907919-ff995280-4476-11eb-84b8-8228b34d5e71.png">

Thank you.

**Comment by fkhadra** [comment]
Hello @NemanjaS2P , the position is determined based on the window size. One solution for your use case would be to use the custom position option as shown in the code sanbox sample
[![Edit react-contexify-#160](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-contexify-160-wsq8i?fontsize=14&hidenavigation=1&theme=dark)
