### ISSUE TITLE
Menu overflows out of screen

### ISSUE THREAD

**Issue by ricardojrgpimentel** [fkhadra/react-contexify#163]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
When the trigger to open the menu is performed,. while the menu is already being displayed, by clicking in the same area, the menu overflows out of screen

https://user-images.githubusercontent.com/12200109/103914249-71bd9880-5101-11eb-83c0-4dcb70772e4b.mp4

**Comment by elartix** [comment]
Same issue, it's appeared when configured animation option for `<Menu>` tag



https://user-images.githubusercontent.com/1899626/106185389-74b12380-61ab-11eb-9de0-72258d56fdd4.mp4

**Comment by geroale** [comment]
Same issue here

**Comment by ShahriarKh** [comment]
I just screen captured this and was going to open a new issue :trollface: 
Well, I have the same issue here.

**Comment by JuanmaMenendez** [comment]
I am having this issue. I am using version 6.0.0 of the library. Any idea what could be happening or what can I do? @fkhadra 
<img width="401" alt="image" src="https://github.com/fkhadra/react-contexify/assets/18317520/71e37873-7907-4539-b5cb-7109ce1857c6">

**Comment by skolix15** [comment]
I have the same issue to the new version (6.0.0) (The image below is from mobile view)

If I right click in the middle of the element then the half of the submenu is going out of view.

Can you help me with that? @fkhadra

![image](https://github.com/user-attachments/assets/3f987949-6b0f-4337-973e-0c80f1851b0a)
