### ISSUE TITLE
<input/> inside <Item/> does not work

### ISSUE THREAD

**Issue by bladl** [fkhadra/react-contexify#168]
I have input inside menu item. onChange event is not firing.
Seems like it is cancelled globally on [this line](https://github.com/fkhadra/react-contexify/blob/master/src/components/Menu.tsx#L182)

**Comment by JaoSchmidt** [comment]
Did you manage to get a working code?

**Comment by l-you** [comment]
@JaoSchmidt 
I had to redesign the UX.
Now, I use a 'More' button alongside with the `@mui/material/Dialog` and `@mui/material/List` components.
Context menus, in general, are considered a bad practice for web and should be avoided, especially for mobile web apps.
