### ISSUE TITLE
Uncaught ReferenceError: process is not defined

### ISSUE THREAD

**Issue by draibolit** [fkhadra/react-contexify#174]
The error happened when Webpack version 5 was used due to the fact that Webpack 5 removed the ability to access environment variables using the notation process.env.MY_ENV_VAR

My temporary solution:
```
npm install -D process
```
and add the following config in Webpack config file:
```
  plugins: [
      new webpack.ProvidePlugin({
             process: 'process/browser',
      }),
  ],

```

**Comment by tarnishablec** [comment]
same error when using vite

**Comment by itsthekeming** [comment]
> same error when using vite

Hey, I encountered this same error and was able to fix it with [this](https://github.com/vitejs/vite/issues/1973#issuecomment-787571499). Not sure what else it might break though.

**Comment by jjshe** [comment]
When use vite

Add the following config in vite config file:

```js
export default defineConfig({
  define: {
    'process.env': {}
  }
})
```

**Comment by JonathanMEdwards** [comment]
Happening with esbuild

**Comment by fkhadra** [comment]
The use of process will be removed.
