### ISSUE TITLE
Update instruction

### ISSUE THREAD

**Issue by brezetsky** [fkhadra/react-contexify#18]
<img width="966" alt="screen shot 2017-05-24 at 11 07 26 pm" src="https://cloud.githubusercontent.com/assets/24649701/26423306/d3603aa6-40d5-11e7-8d28-654c6bec1641.png">

**Comment by fkhadra** [comment]
Which instruction needs to be updated?

**Comment by brezetsky** [comment]
Just here https://github.com/fkhadra/react-contexify
just update react-toatify to react-contexify

**Comment by fkhadra** [comment]
Didn't even notice that one. Fixed now.
Many thanks by the way
