### ISSUE TITLE
Position problem occurred after portal being dropped.

### ISSUE THREAD

**Issue by ETRick** [fkhadra/react-contexify#195]
'position: fixed' will perform like 'position: absoulate' when beding child of node with 'tranform'. This is what I met when update react-contexify to 5.0.0：When I modified react-contexify element' style left, top to '0', it only stiky to the left top of it's parent: 
![20210720183355](https://user-images.githubusercontent.com/7297417/126309861-3839302a-2a0d-4755-9f2b-05f725f1cf11.jpg)

Here's discussion on stackoverflow: https://stackoverflow.com/questions/2637058/positions-fixed-doesnt-work-when-using-webkit-transform

Here's my example: https://codesandbox.io/s/react-contexify-menu-position-error-forked-te0ug

https://github.com/fkhadra/react-contexify/blob/5a5a1b50e7056debb3b167985efbc33f422bb5b0/src/components/Menu.tsx#L315

**Comment by ETRick** [comment]
Here's discussion about position fixed and tranform: [Positions fixed doesn't work when using -webkit-transform] (https://stackoverflow.com/questions/2637058/positions-fixed-doesnt-work-when-using-webkit-transform)

**Comment by fkhadra** [comment]
Hey sorry for the late reply, to get the old behavior this is documented here https://fkhadra.github.io/react-contexify/mount-menu-at-specific-place. I'm currently working on the next major release, I'll make it more obvious
