### ISSUE TITLE
Does the latest version 5.0.0 support Internet Explorer

### ISSUE THREAD

**Issue by selvaganapathy5995** [fkhadra/react-contexify#199]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

The context menu is not opening on the right click.

**What is the expected behavior?**

It should load the context menu.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React version: 16.8.6

**Comment by fkhadra** [comment]
Hey, a bit late :(. I'm working on the next major release, I don't think I ever tested the library with IE. I don't intend to support it
