### ISSUE TITLE
Context Menu Flashes Briefly After Hide (React 18 Batched Updates Issue)

### ISSUE THREAD

**Issue by sotarules** [fkhadra/react-contexify#219]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-contexify@5.0.0` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-contexify/dist/react-contexify.esm.js b/node_modules/react-contexify/dist/react-contexify.esm.js
index 5a371f7..90b5321 100644
--- a/node_modules/react-contexify/dist/react-contexify.esm.js
+++ b/node_modules/react-contexify/dist/react-contexify.esm.js
@@ -1,4 +1,5 @@
 import React, { useContext, createContext, useRef, useEffect, Children, cloneElement, useReducer, useState } from 'react';
+import ReactDOM from 'react-dom';
 import cx from 'clsx';
 
 function _extends() {
@@ -520,12 +521,14 @@ var Menu = function Menu(_ref) {
   }
 
   function handleAnimationEnd() {
-    if (state.willLeave && state.visible) {
-      setState({
-        visible: false,
-        willLeave: false
-      });
-    }
+    ReactDOM.flushSync(() => {
+      if (state.willLeave && state.visible) {
+        setState({
+          visible: false,
+          willLeave: false
+        });
+      }
+    })
   }
 
   function computeAnimationClasses() {
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by supriome** [comment]
Thanks. @sotarules And I have a question, do we need to change this file `react-contexify.cjs.production.min.js` to use `react-contexify` in produciton.

**Comment by sotarules** [comment]
@supriome no sorry you only have to patch the ESM.  I am going to alter that comment to get rid of the CJS patch, that was just me experimenting.  I could not figure out which file I had to change.

**Comment by yuri2peter** [comment]
@sotarules Thanks, that patch fixed my problem.
