### ISSUE TITLE
click event not triggered when click menu item

### ISSUE THREAD

**Issue by lianyzhou** [fkhadra/react-contexify#221]
![bug](https://user-images.githubusercontent.com/6295633/199900182-b2cb4072-2271-4931-abb9-1adba542fce7.gif)

i found a bug with react-contexify， when user select some text in the input , then trigger context menu , and then click the menu item, the item will not trigger the click event。

but when i changed the click event to mousedown , the problem solved， it is wired，but real exist.

![image](https://user-images.githubusercontent.com/6295633/199900770-0299bc60-2619-4655-a685-fe004e83e9c3.png)

it is nice to provide a option handlerEventName，default value is onClick， when wired situation meets, developer can change it to onMouseDown。

Thanks to react-conextify, it saves my time on building context menu ui widgets.

**Comment by fkhadra** [comment]
Hey @lianyzhou, it will be available in the next release https://github.com/fkhadra/react-contexify/pull/220 I'm currently working on it
