### ISSUE TITLE
Cannot read property of 'offsetWidth' of null

### ISSUE THREAD

**Issue by ali-stratoscale** [fkhadra/react-contexify#23]
When I try to create a menu and right click on said MenuProvider I get thrown with the following error in the console. It seems that this.menu is null and it is trying to access a value of a null object.

I am not sure if I did something wrong, or they should have been a default value for it?

**Comment by ali-stratoscale** [comment]
It was an issue with my setup, sorry for the trouble.

**Comment by fkhadra** [comment]
@ali-stratoscale np
