### ISSUE TITLE
May I have the demo's source code?

### ISSUE THREAD

**Issue by toyang** [fkhadra/react-contexify#25]
hello, May I have the demo's source code?

**Comment by fkhadra** [comment]
Hello @toyang,

Of course, the sources are located under the [gh-source branch](https://github.com/fkhadra/react-contexify/tree/gh-sources).

The code is not the cleanest don't hesitate if you have questions!

**Comment by toyang** [comment]
Thanks a lot .It is useful for me

**Comment by bytrix** [comment]
hello, @fkhadra,
is there a demo of that gif image shown on the github page?
[https://user-images.githubusercontent.com/5574267/29753912-43c54008-8b7b-11e7-9627-258fde1ffddd.gif](url)
