### ISSUE TITLE
Getting "flattenChildren" error when upgrading from 2.0.7 to 2.1.2

### ISSUE THREAD

**Issue by jktravis** [fkhadra/react-contexify#33]
Hi, Any idea why I would just start getting the `flattenChildren(...): Encountered two children with the same key, 'journal-menu'.` error after upgrading from 2.0.7 => 2.1.2? 

As far as I can tell, there's no iteration or lists of components going on where I'm using it except for where I'm using the `ContextMenuProfider`.

```jsx
const JournalListItem = ({item}) => {
  const journalId = item.get('Id');
  return (
    <li data-id={journalId}>
      <ContextMenuProvider id="journal-menu">
        <Link to={`/journal/${journalId}`}>{item.get('Name')}</Link>
      </ContextMenuProvider>
    </li>
  );
};
```

Here's the whole message:

```
Warning: flattenChildren(...): Encountered two children with the same key, `journal-menu`. Child keys must be unique; when two children share a key, only the first child will be used.
    in div (created by ProxyContainer)
    in ProxyContainer
```
It looks like there was a ProxyContainer recently added. Could this be it adding duplicate keys, or am I just using it wrong now?

**Comment by fkhadra** [comment]
Hey @jktravis,

Can you check the content of the ProxyContainer state with the react devtools? 
<img width="576" alt="screen shot 2017-09-06 at 20 48 07" src="https://user-images.githubusercontent.com/5574267/30128970-c47760f2-9344-11e7-85f3-995ee93dfe89.png">

Is there any issue with the keys ?

**Comment by jktravis** [comment]
Yup. It does, indeed, look like they are the same.

![2017-09-06_14-59-07](https://user-images.githubusercontent.com/438688/30129512-192bdc1c-9314-11e7-8ed3-91be399ad394.jpg)

**Comment by jktravis** [comment]
What's weird is there's only one `journal-menu` on the page anyway. And it only has 2 list items. But it looks like these elements were being created 5 times. Maybe one for each render or something?

**Comment by fkhadra** [comment]
OMG forgot to remove the context menu from the container when it's unmounted

**Comment by fkhadra** [comment]
@jktravis I fixed the issue. Sorry for the inconvenience!
