### ISSUE TITLE
Menu rendering off screen

### ISSUE THREAD

**Issue by hansena** [fkhadra/react-contexify#35]
On right click i can see the dom nodes render and left click makes them go away but the menu renders off screen..   Has anyone else seen this behavior?

![menuoffscreen](https://user-images.githubusercontent.com/15346521/30755039-11e9f458-9f93-11e7-914f-a7bee8ab8138.png)

**Comment by fkhadra** [comment]
Hey @hansena, when you say that the menu renders off-screen, you are talking about the dom nodes or the menu itself?

**Comment by hansena** [comment]
Sorry I'm seeing the dom nodes render in chrome dev tools.  The menu appears to be off-screen
