### ISSUE TITLE
Is there any way to programmatically open context menu?

### ISSUE THREAD

**Issue by krzychukula** [fkhadra/react-contexify#37]
I have an component that based on position (mousemove) should use different data in context menu.
One way that I could work around it is to use my own contextmenu event handler and to open context menu like `openContextMenu('menu_id', someData)` that I could use later on in `Item` `onClick`.

Another would be to have some kind of 'onBeforeContextMenuOpen` where I could calculate data to be passed to context menu.

Btw. right now I'm using ref to pass data to `Item.onClick` and I don't really need custom data from 'Item' but it would be great to have custom data passed to ContextMenuProvider passed on `Item.onClick` handler.

**Comment by fkhadra** [comment]
Hello @krzychukula,

Actually there is no way to trigger the context menu programmatically. 

To be honest the current api is missing some features(nested menu, hooks...).

I'm planning to work on the component this week. I'll see what I can improve.

**Comment by krzychukula** [comment]
@fkhadra I have one more question. 
I have mousemove handler close to the context menu with similar looking tooltip with some detailed information. Unfortunately it looks super confusing when I open context menu. 
Any suggestions for blocking disabling it?

I can think of 2 ways of implementation
1. Some kind of overlay div with my own mousemove preventing event propagation.
2. Reading 'opened' state of context menu and disabling entire layer/div from rendering when contextmenu is open.

If you have any other suggestions please let me know. Right now I'm trying to figure out if my use case is special enough so that I have to write my own contextmenu so if you think it's out of scope of react-contextify then please let me know. No pressure :)

**Comment by fkhadra** [comment]
@krzychukula that's an interesting use case. My first thought would be to not render the tooltip when the context menu is displayed.

You need a way to track the context menu state, unfortunately, the current implementation lacks these kinds of features 😢.

I'll review the api but not now, need to find a window for that.

Did you tried [react-contextmenu](https://github.com/vkbansal/react-contextmenu/). The [api](https://github.com/vkbansal/react-contextmenu/blob/master/docs/api.md) is more mature and I think it suits better for your use case.

**Comment by krzychukula** [comment]
@fkhadra Thanks I'll take a look :)
