### ISSUE TITLE
I want to user contexify lib into my app can u help me to implement

### ISSUE THREAD

**Issue by kamaldlk** [fkhadra/react-contexify#38]
Hi @fkhadra 
example https://codesandbox.io/s/3z3lq9zn1 

thanks for nice lib

please when i click right click **add row above, add row bellow and delete row** 
when i select multi rows using check box i want to show **delete all** text need to show please suggest me 

thanks

**Comment by fkhadra** [comment]
Hey @kamaldlk,

Thank for your feedback. 
But the context menu used by react-data-grid is not mine 😁 
The one used is [here](https://github.com/vkbansal/react-contextmenu).

**Comment by kamaldlk** [comment]
Ya i seen his example but i like it your approach that's y i asked u @fkhadra

**Comment by fkhadra** [comment]
Ok I understand. I'll check how it can be implemented. 

Keep in mind that my lib don't allow nested menu for the moment 😢

**Comment by kamaldlk** [comment]
Ha Ha ok no problem i like ur lib animations and single menu

**Comment by fkhadra** [comment]
You can define the menu on the row or by cell depending on your use case.

The first snippet define a context menu only on firstname cell. 
[![Edit 6zv1229w0k](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/6zv1229w0k)

The second one use the context menu for all row.
[![Edit 0o6z6rry4l](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/0o6z6rry4l)

I need to push a fix so you can define style or className as props for the ContextMenu component.
But for the moment I created a file `index.css` to set the `z-index`

**Comment by kamaldlk** [comment]
Very Very Thanks Brother your so awesome 💯  👍

**Comment by fkhadra** [comment]
You're welcome.

I don't use skype at all. You can find me on [linkedin](https://www.linkedin.com/in/fadikhadra/)

**Comment by kamaldlk** [comment]
Brother getting problem while scrolling becoz of rowrender do we have any other chance

**Comment by fkhadra** [comment]
What do you mean ?

**Comment by kamaldlk** [comment]
if u scroll horizontal u will   know the issue broher
