### ISSUE TITLE
Support css-modules

### ISSUE THREAD

**Issue by Lefortov** [fkhadra/react-contexify#48]
Hi

I have noticed that now if you use css modules in your project and import styles from contexify context menu would not work until setting contexify styles globally. Are there any chances to support css-modules?

Thanks

**Comment by fkhadra** [comment]
Hello @Lefortoc

I'll work on it when I release the stable v3. Thanks for the feedback.

**Comment by shiny** [comment]
Any progress on this feature?

**Comment by fkhadra** [comment]
@shiny not at all.Too busy 😭. Wanna make a PR ?
