### ISSUE TITLE
document is not defined error when rendering server side

### ISSUE THREAD

**Issue by almeynman** [fkhadra/react-contexify#51]
I have ssr setup and I receive `document is not defined error`
The error fires from `withProxy`hoc's componentWillMount hook.

**Comment by fkhadra** [comment]
Hello,

I'll fix it asap.

**Comment by almeynman** [comment]
Thanks

**Comment by fkhadra** [comment]
Hello @almeynman,

The fix is live

**Comment by almeynman** [comment]
Thanks, I will check on Monday
