### ISSUE TITLE
Hope prevent contextmenu event on ContextMenu component

### ISSUE THREAD

**Issue by hb-bobo** [fkhadra/react-contexify#52]
1.Hope prevent contextmenu event on ContextMenu component
2. if (e.keyCode === 27 || e.keyCode === 13) { // ECS or enter
            // hideMenu
        }

**Comment by fkhadra** [comment]
Hey @hb-bobo,

Thanks for the suggestion.

**Comment by fkhadra** [comment]
Hello @hb-bobo,

The feature has been added
