### ISSUE TITLE
Hide menu on condition

### ISSUE THREAD

**Issue by Anandks1993** [fkhadra/react-contexify#56]
Hi

On clicking of item, the context-menu disappears, but is there any way that we can control the hiding of context-menu ? Because I want to accommodate a form inside the context-menu. Thanks in advance

**Comment by fkhadra** [comment]
Hello,

For the moment, it's not possible. But i'll think about it.

**Comment by Anandks1993** [comment]
@fkhadra Thank you .

**Comment by rebirthtobi** [comment]
@fkhadra I'm also in need of this feature, dynamic open and closing of the context menu and do nothing when menu item is clicked

**Comment by rohitkrishna094** [comment]
Any update on this? is it possible to do this now?
