### ISSUE TITLE
Cannot read property 'offsetWidth' of null

### ISSUE THREAD

**Issue by codegeous** [fkhadra/react-contexify#58]
When I right click to open the context menu there was an error in the console  "Uncaught TypeError: Cannot read property 'offsetWidth' of null". Please find the attached image for more information.

![image](https://user-images.githubusercontent.com/26200908/38291366-0abc327e-37fd-11e8-9f01-575535a89758.png)

But the context menu is working as expected.

**Comment by fkhadra** [comment]
Hey @codegeous,

Could you show me a sample of your app ?

Thanks

**Comment by codegeous** [comment]
I cannot share the complete app right now. So here is the GIST for the code that i use.

[https://gist.github.com/codegeous/2709aecf50f0adeb2adc3a223ffc6b8b](https://gist.github.com/codegeous/2709aecf50f0adeb2adc3a223ffc6b8b)

**Comment by ricardojrgpimentel** [comment]
Im getting the same problem

**Comment by MadeoIT** [comment]
Same problem here

**Comment by fkhadra** [comment]
I tried with the gist above but it works in my case. @MadeoIT can you share the code in your case ?

Thanks

**Comment by MadeoIT** [comment]
Looks like it this error appears only in certain cases. I will look more into it and let you know

**Comment by priyadarshy** [comment]
I am having the same issue when I render things in a loop.

**Comment by fkhadra** [comment]
Hello @priyadarshy,

Is your contextmenu id unique ?

**Comment by kunokdev** [comment]
I had this error and by making id's unique it would be gone.

**Comment by chriscordi** [comment]
@fkhadra I think a better proposed fix than setting unique ids is to have a chunk of demo code that shows using a single ContextMenu that is added to the page _outside_  of the loop, with the only ContextMenuProviders being created on a per-element basis and having the unique part being instead passed in with the Provider's data prop.

**Comment by fkhadra** [comment]
Thanks for the feedback. @chriscordi if you have time to make a demo on codesandbox don't hesitate to submit a PR with the url, so I can add it to the documentation

**Comment by subwaymatch** [comment]
@chriscordi Had the same issue while creating context menus within a loop. Thanks for pointing out the issue. Saved a hell lot of time :)
