### ISSUE TITLE
Need help to integrate contextify with react d3-tree

### ISSUE THREAD

**Issue by isrplo** [fkhadra/react-contexify#59]
Hi There,
I'm not sure this is the correct place to ask for help, sorry in advance if it isn't.
I am new to React, so sorry for the crudity...
I am trying to integrate the contextify with react d3-tree component (which basically draws a tree).
I would like to couple the menu item to the tree node, while I am standing over it.
the problem is that I don't have explicit accsess to tree elements. what I do have is the onClick and onMouseOver callbacks which fires back the node in question.
Is there a way to somehow update the menu uppon mouseover event, or am I doomed?

Thanks,
Jonathan

**Comment by fkhadra** [comment]
Hey @isrplo,

It's an interesting use case you have here. Could you share a snippet on codesanbox or even a repo ?

**Comment by fkhadra** [comment]
Thanks for the quick reply, i'll have a look asap.

**Comment by fkhadra** [comment]
Hey @isrplo,

Could you check this sample and tell me if it's what you are looking for?

[![Edit 9j3r2oxnmo](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/9j3r2oxnmo)

Thanks

**Comment by isrplo** [comment]
Hi,
Not quite,
I would like to know over which node the menu was called, so the onClick callback would implement different logic based on that tree node. 

Thanks!

**Comment by isrplo** [comment]
oh, scratch my last comment! I just had to add data to ContextMenuProvider! it works a treat now!

Thanks so much for your help!

**Comment by fkhadra** [comment]
@isrplo I updated the code. You can pass props to the `ContextMenuProvider`. I passed down a random id. What you could do is to add an id to your data and pass the id down like:

```js
<ContextMenuProvider data={ { id: nodeData.id } } >
```
[![Edit 9j3r2oxnmo](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/9j3r2oxnmo)

**Comment by fkhadra** [comment]
Good timing 😁

**Comment by isrplo** [comment]
indeed :)
Thanks again!
