### ISSUE TITLE
Warning: Unknown prop `render` on <li> tag. Remove this prop from the element

### ISSUE THREAD

**Issue by OlegPinchuk** [fkhadra/react-contexify#60]
Hi, I got strange warning, may be i use wrong implementation or something else. Please check.
my code:

```import React, { Component } from 'react';
import PropTypes from 'prop-types';
import moment from 'moment';
import { withStyles } from 'material-ui/styles';
import stylesFunc from './ChatTextMsg.styles';
import { ContextMenu, Item, Separator, Submenu, ContextMenuProvider } from 'react-contexify';

const styles = theme => (stylesFunc(theme, scrollWidth()));

class ChatTextMsg extends Component {
  constructor(props) {
    super(props);
    this.state = {};
  }

  renderMessage({ files, created, from }) {
    const { classes } = this.props;
    const time = moment(created).format("HH:mm:ss A");

    return (
      <ContextMenuProvider id="text_bubble">
          <li className={ classes.messageItem }>
            <p>{
              //render text data
            }</p>
            <p className={classes.messageTime}>{ time }</p>
          </li>
      </ContextMenuProvider>

    )
  }

  render() {
    const { classes, data, activeDialogId } = this.props;

    return (
        <ul className={data.from === activeDialogId ? `${classes.messageList} his-list` : `${classes.messageList}`}>
          { this.renderMessage(data) }
        </ul>
    )
  }
}

ChatTextMsg.propTypes = {
  classes: PropTypes.object.isRequired
};

export default withStyles(styles)(ChatTextMsg);
```

**Comment by fkhadra** [comment]
Hello @OlegPinchuk,

The `ContextMenuProvider` render a div tag by default. With your implementation, your dom will look like this:

```js
<ul>
  <div>
     <li>lorem ipsum</li>
  </div>
</ul>
```

You have two choices to solve your problem.

1- Use a render props:
```js
<ContextMenuProvider id="menu_id" render={({ children, ...rest  }) => ( 
       <li className={ classes.messageItem } {...rest}>
          {children}
       </li>
)>
    <p>{ //render text data}</p>
    <p className={classes.messageTime}>{ time }</p>
</ContextMenuProvider>
);
```

2-Change the default render tag:
```js
<ContextMenuProvider id="menu_id" component="li" className={ classes.messageItem }>
  <p>{
          //render text data
  }</p>
   <p className={classes.messageTime}>{ time }</p>
  </ContextMenuProvider>
```

You can even pass a custom component to the component props if you want to. I guess in your case it is best to stick with the second choice but it's up to you.

Hope that help 😀

**Comment by OlegPinchuk** [comment]
@fkhadra Yeah, thanks a lot ! I hope it will help)

**Comment by OlegPinchuk** [comment]
@fkhadra 1st point works well!

**Comment by fkhadra** [comment]
@OlegPinchuk Perfect!

**Comment by marjo688** [comment]
Hi! 
I have the same issue as @OlegPinchuk, only difference being the warning references a <div> instead of a <li> element. I have tried your solutions proposed in this issue but the warning remains.

My code, with your solution implemented (2), looks as follows:

`    render() {

        const listItems = this.state.noteArray.map((note, i) =>

            <ContextMenuProvider id="menu_id" component="li" className="noteList" key={note._id}>
                <div id={note._id} className="cheatNote" onClick={() => this.updateNote({ note })}>

                    <div className="noteTitle">{note.title}</div>

                    <div className="frontNoteText">{note.show ? note.answer : note.question}</div>
                </div>
            </ContextMenuProvider>

        );

        return (
            <Grid fluid={true}>

                <p onClick={e => this.goBack()}>Go back</p>

                <ul>{listItems}</ul>
                <ContextMenu id='menu_id'>
                    <Item onClick={this.onContextMenuDelete}>Delete</Item>
                </ContextMenu>

            </Grid>
        );
    }
}`

Is there something wrong with my implementation or anything else I misunderstood or misinterpreted

**Comment by marjo688** [comment]
Realised I referenced the elements a bit silly. To clarify the error references a div instead of a li element!
