### ISSUE TITLE
Add anchor-element to align context-menu to

### ISSUE THREAD

**Issue by misantronic** [fkhadra/react-contexify#63]
It would be really nice to tell the `ContextMenuProvider` that the position where the context-menu opens is not the mouse but the actual element which is provided to the `ContextMenuProvider`.
And then a position would be cool like `top`, `bottom` etc.

**Comment by misantronic** [comment]
Here is a suggestion:
https://github.com/fkhadra/react-contexify/pull/64

**Comment by fkhadra** [comment]
possible since v5 with custom position
