### ISSUE TITLE
Warning: Unknown prop `render` on <i> tag.

### ISSUE THREAD

**Issue by mjohnson290** [fkhadra/react-contexify#65]
I've seen this issue reported on #60 but after trying the two methods to remedy it I've come up short.

Basically the goal is to have a single <i> element as the context trigger. 

I've tried
- passing in a "i" as a component prop and applying className to the ContextMenuProvider for my desired <i> styles
- creating a custom component (just a <div> to hold it) and passing it under the component prop, but I still get the same error

`<ContextMenuProvider id={singleBookmark} event="onClick" className={s.singleContextContainer}>`
`  <i className="fa fa-cog" aria-hidden="true" />`
`</ContextMenuProvider>`

Any idea if I'm doing something fundamentally wrong here? Thanks for any help!

**Comment by AlanAdmin** [comment]
I have the same question. The 2 methods in #60 I have already tried didn't work yet.

**Comment by fkhadra** [comment]
Hello,

Sorry for the late reply. I tried to reproduce your issue without success. The sample work as expected:
[![Edit lpj0qmm647](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/lpj0qmm647)

Could you tell me exactly what error do you have?

Thanks

**Comment by marjo688** [comment]
Late input, but the reason I got the warning because my project were using React 15. Upgrading to 16 fixed the issue.

**Comment by fkhadra** [comment]
Thank you @marjo688 for the information.

**Comment by fkhadra** [comment]
@mjohnson290 did you try to upgrade react like @marjo688 suggested?
