### ISSUE TITLE
Event is not registered. Did you forgot to bind the event ?

### ISSUE THREAD

**Issue by jkeruzec** [fkhadra/react-contexify#72]
Hello, 
I'm trying to make context menu work but I have some issue when I right click on my text that should display the context menu :
`js <display::menu> Event is not registered. Did you forgot to bind the event ?`

```
const myMenu = () => (<ContextMenu id="menu">
                          <Item >Ipsum</Item>
                       </ContextMenu>);
        
        return {icons: [
                <div
                style={iconStyle}
              />,
            ],
            title : 
                     <div>
                          <ContextMenuProvider id="menu">
                          <span>{rowInfo.node.title}</span>
                          </ContextMenuProvider>
                          {myMenu}
                          </div>
                          ,
            onClick: event => this.nodeClicked(event, rowInfo),
            style : innerStyle
        };
```

I'm using it with react-sortable-tree to add a contextual menu on my items...

Thanks !

**Comment by fkhadra** [comment]
Hello @jkeruzec,

Could you share your snippet on code sandbox please? So I can help you.

Thanks

**Comment by jkeruzec** [comment]
Hello @fkhadra,
Thanks for your answer, I just created a codesandbox for you to test the issue :
[https://codesandbox.io/s/7oj4v5747j](https://codesandbox.io/s/7oj4v5747j)

You just have to right click on the text "Chicken" or "Egg" to trigger the problem... demo.js file.

On the console : 
`<display::menu> Event is not registered. Did you forgot to bind the event ? `

**Comment by fkhadra** [comment]
Hey @jkeruzec,

I forked your sample here: [![Edit yw6zwjz2zv](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/yw6zwjz2zv)

You'll notice that I rendered the `ContextMenu` after the `SortableTree` Component.

In your case, for each tree element you where rendering a `ContextMenu`. ContextMenu needs to be unique which was not the case with your implementation.

Please tell me if the explaination are clear enough.

**Comment by jkeruzec** [comment]
Ok clever see!, I already tried it in my implementation to add unique id for menu but I was mistaken by a wrong z-index .... !!


Thanks your lighting fast help :)

**Comment by jerrythimothyj** [comment]
@fkhadra , I am facing this issue `<DISPLAY_var_20> Event is not registered. Did you forgot to bind the event ?`

I am dynamically adding an element which contains Menu component inside it. I am passing id like this `<Menu id={menuId}>` which is always unique like a key.

If I inspect via React console, everything seems same as the already generated elements.

But, when I click try to open the context menu from the newly created element, I get that error.

I cannot find the dynamically created entry in the `eventList` Map in `eventManager_1.eventManager` .

**Comment by ngoctigerstyle** [comment]
@jerrythimothyj : i have same problem.

**Comment by nara007** [comment]
@jerrythimothyj @ngoctigerstyle   take an table as an example,   you can create one MenuProvider instance for each row, when you right click on each row, a menu will be shown. **However, you are allowed to create only one Menu instance,  all rows share the instance**

<Table>
{ create table row,  bind MenuProvider(id== 'menu_id')to each row }
</Table>
<MyAwesomeMenu id='menu_id'>

**Comment by temp-noob** [comment]
> @jerrythimothyj @ngoctigerstyle take an table as an example, you can create one MenuProvider instance for each row, when you right click on each row, a menu will be shown. **However, you are allowed to create only one Menu instance, all rows share the instance**
> `<Table>`
> `{ create table row, bind MenuProvider(id== 'menu_id')to each row }`
> `</Table>`
> `<MyAwesomeMenu id='menu_id'>`

@nara007  I actually want to achieve the same use case of using a context menu for each table row. I'm new to React. Can you provide a small code snippet that would achieve this?

**Comment by aditya-padhi-kbl** [comment]
@nara007 I am not able to understand the above statement but still I am getting the issue as pointed out by @jerrythimothyj @ngoctigerstyle 
To a chart I am adding the instance as 
```
chart: {
                                    zoomType: this.widgetProps.zoomEnabled ? 'xy' : undefined,
                                    events: {
                                        load: function () {
                                            let chart = this;
                                            let legend = chart.legend;
                                            let {allItems = []} = {...legend};
                                            let allItemsLength = allItems.length;
                                            for (let i = 0; i < allItemsLength; i++) {
                                                ((i) =>  {
                                                    let item = allItems[i].legendItem;
                                                    item.on('contextmenu', event => {
                                                        contextMenu.show({
                                                            id: "metricRightClickMenu",
                                                            position: {
                                                                x: 0, y: 0
                                                            },
                                                            props: {
                                                                key: "value",
                                                                payLoad: chart
                                                              },
                                                              
                                                            event
                                                        });
                                                        event.preventDefault();
                                                        event.stopPropagation();
                                                    });
                                                })(i);
                                            }
                        
                                        }
                                    }
                                }
```

and I have declared the ID as 
```
<Menu id="metricRightClickMenu" onShown = {this.shownEvent} onHidden = {this.hiddenEvent}>
                        <Item  onClick = {(e) => cchangeEvent(e, 'showOnly')}> 
                        <Button size="small" type="link">Show Only</Button>
                        </Item>
                        <Item onClick = {(e) => cchangeEvent(e, 'selectAll')}>
                        <Button size="small" type="link">Select All</Button>
                        </Item>
                        
                    </Menu>
```
