### ISSUE TITLE
How to use react-contexify with react-intl?

### ISSUE THREAD

**Issue by GersonDias** [fkhadra/react-contexify#73]
Hello! 

Since the component is appended to the body, it lives outside the boundary of IntlProvider or any other "provider-ish" like react-redux provider or react-router... so, what is the best way to provide internationalization features to react-contexify? 

![image](https://user-images.githubusercontent.com/1994582/42573892-9a97cbfc-851d-11e8-92c3-5590f7806ba0.png)

**Comment by fkhadra** [comment]
Hello @GersonDias,

I'm not familiar with react-intl, I took a look at the documentation. I tried to make something but I failed. I'll try later if I can free more time. Did you try to google something like react portal react-intl ?
