### ISSUE TITLE
Add a ContextMenu on Google Map Polygon

### ISSUE THREAD

**Issue by muwednesday** [fkhadra/react-contexify#74]
Hello, I have learning on Google Map APIs and want to add a a contextmenu in drawing polygons using React. Since the polygon does not exist utill user finish drawing it, I don't know how to handle this problem, I would appricate if you could help me.
I need to bind a rightclick event in Google Map DrawingManager's onPolygonComplete event, in this funtion:
```
const handlePolygonComplete=function(polygon){
// add a contextmenu in polygon
};
```

**Comment by fkhadra** [comment]
Hello @muwednesday,

May I ask you to put a sample on codesanbox ? 

Thanks

**Comment by muwednesday** [comment]
Thanks for replying. [Here is the link](https://codesandbox.io/s/zwxmkxz66x).
You can draw a polygon using the drawingmanager from top_center of the map. I want the contextmenu only tiggering in the polygon.
![image](https://user-images.githubusercontent.com/34086410/43242191-20b1c5c0-90d2-11e8-8a35-e19f30a15005.png)

**Comment by fkhadra** [comment]
Hello @muwednesday,

I don't know if you are still looking for a context menu to use with google map polygon. Anyway, I'm working on the next version. 
It will be easier to integrate the contextmenu.
