### ISSUE TITLE
Usage of componentWillReceiveProps() is unsafe, results in empty render.

### ISSUE THREAD

**Issue by gokcan** [fkhadra/react-contexify#76]
Hi @fkhadra,

Unconditionally calling `this.removeFromBody()`  and ` this.appendToBody(this.props)` on `componentWillReceiveProps()` results inconsistent behavior on List items. 

https://github.com/fkhadra/react-contexify/blob/20be6cad773d5ee251add45cfb0ed00d30c98bff/src/util/withProxy.js#L16

This can be easily solved with:

```javascript
function componentDidUpdate(prevProps) {
  if (prevProps !== this.props) {
    this.removeFromBody();
    this.appendToBody(this.props)
   }
}
```

Let me know if you agree on this, I can send a PR.

**Comment by fkhadra** [comment]
Hey @gokcan,

Would appreciate if you can work on a PR. I'm busy updating all the dependencies for the moment.

**Comment by fkhadra** [comment]
Hey @gokcan,

The v4 remove the proxy and use `react.portal` instead.
