### ISSUE TITLE
ContextMenuProvider and other component handlers used together

### ISSUE THREAD

**Issue by Khyzz** [fkhadra/react-contexify#79]
Hello,

I'm using a timeline React component that already handle the context menu events in a good way. 

```
onItemContextMenu = (itemId, e, time) => {}
   
onCanvasContextMenu = (group, time, e) => {} 

<Timeline
                        ref={r => { this.timeline = r; }}
                        onItemContextMenu={this.onItemContextMenu}
                        onCanvasContextMenu={this.onCanvasContextMenu}
>
```

The fact is that I need theses handler's arguments, so I need my context menu to trigger thanks to the Timeline component.

Here is the problem : react-contexify needs a contextmenuProvider to trigger and the event it gets isn't the one I'd like to have. But I still need this ContextMenu to display from my handlers.

Is there a way to pass through the contextmenuProvider and simply render my ` <ContextMenu>` component in `onCanvasContextMenu` or in `onItemContextMenu` . Or maybe I can simulate an event to always trigger the Provider when entring handlers.

(Sorry, tell me if my approximate english makes it unclear)

**Comment by fkhadra** [comment]
Hello @Khyzz,

You can define which event  should trigger the contextMenu see [here](https://github.com/fkhadra/react-contexify#contextmenuprovider).

Is it what your are looking for ?

**Comment by Khyzz** [comment]
Well, I'd like this but with an always `true` event then.

**Comment by fkhadra** [comment]
Hey,

Could you create a codesanbox so I can help ?

Thanks.

**Comment by Khyzz** [comment]
So,

Here is a sandbox https://codesandbox.io/embed/9l6rx3jxmp. I hope it will make it clear.

Thanks for your reactivity.

**Comment by fkhadra** [comment]
I understand now what you are trying to do. I think that with the current implementation is not feasible. I should expose something to trigger the contextmenu without using the provider. Let me think about it and I'll be back to you.
I also need to upgrade the library so it will be a good opportunity.

**Comment by Khyzz** [comment]
Alright thanks a lot for your attention and for this plugin.

**Comment by fkhadra** [comment]
Hey @Khyzz,

I released the v4-rc1. You have now the possibility to do something like:

```js
contextMenu.show({
event: e,
id: menuId,
props: myProps
});
``` 

You can find a sample with a canvas [here](https://fkhadra.github.io/react-contexify/you-dont-need-the-menu-provider)
