### ISSUE TITLE
Get active row from react table

### ISSUE THREAD

**Issue by ticholNyler** [fkhadra/react-contexify#82]
I had to wrap the entire react table in the context component. There for the ref.props is returning the main react table. I can not seem to figure out how to get the selected row when right clicking. Is this possible as the component is written?

**Comment by fkhadra** [comment]
Hey @ticholNyler,

I'm planning to release a new version of react-contexify this week. It will be easier to integrate.

**Comment by fkhadra** [comment]
Hey @ticholNyler,

I released the v4-rc1. I introduced a new api to give more control.

**Comment by omkar-joshi** [comment]
The `ContextMenu` API is awesome @fkhadra. Thanks!

**Comment by fkhadra** [comment]
Thanks @omkar-joshi for the feedback. I'll probably publish the stable release this week.

**Comment by baurais** [comment]
@ticholNyler Did you manage to find a work around?
