### ISSUE TITLE
Webpack error

### ISSUE THREAD

**Issue by pniedzwiedzinski** [fkhadra/react-contexify#85]
An error occurs when I bundling with webpack
```
ERROR in ./node_modules/react-contexify/dist/ReactContexify.css 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
> .react-contexify {
|   position: fixed;
|   opacity: 0;
```

**Comment by fkhadra** [comment]
Hey @butterfly-pn,

It's related to webpack, you need to use the style-loader and the css-loader. If you bootstrap an app with create-react-app, it should work out of the box.

**Comment by butterfly-pn** [comment]
Could you please send me an example of webpack configuration? I just can't make it work 😩

**Comment by perry-mitchell** [comment]
@pniedzwiedzinski You're excluding node_modules in your config - That's where you're trying to import from, so I would remove the exclude line.
