### ISSUE TITLE
Rename Component in Doc

### ISSUE THREAD

**Issue by gokusanSK** [fkhadra/react-contexify#87]
When i am using this library according to doc it says to use ContextMenuProvider but in defination the exported module name in MenuProvider similarly with ContextMenu->Menu

**Comment by fkhadra** [comment]
Hello @gokusanSK,

You are using the v4, it's a release candidate. You can find the doc [here](https://fkhadra.github.io/). If you see the old site you probably need to clean the service worker(I still need to fix this issue.).

You should see something like the screenshot below. Please let me know if you have any issue.
![2018-10-29_10-58-58](https://user-images.githubusercontent.com/5574267/47642739-b3d61180-db69-11e8-823b-7afe7ff7424b.png)
