### ISSUE TITLE
Is there any way to not have menu close when clicked?

### ISSUE THREAD

**Issue by evansjohnson** [fkhadra/react-contexify#91]
In the `onClick` event handler of `Item` I have tried calling `stopPropagation` and `preventDefault` on the event and the menu still closes.

I see [here](https://github.com/fkhadra/react-contexify/blob/c0f6fb8f5d20d5404e51f12d9337c4284cf397a7/src/components/Menu.tsx#L90) that a `mousedown` event is bound to `window` as well as `onClick` - a guess is that I am preventing the `onClick` event from calling hide but the `mousedown` event hides the menu anyways.

In my use case I want to use Items as filter options, and I want the user to be able to select multiple options without re-opening the menu between each selection.

**Comment by evansjohnson** [comment]
Tried removing the line that attaches the mousedown listener to window and that didn't work.  Any ideas you have on this would be greatly appreciated!

**Comment by fkhadra** [comment]
With the current implementation is not possible. However, it's easy to implement, all I need to do is to stop propagation on the synthetic event. This is what I do for the disabled Item [here](https://github.com/fkhadra/react-contexify/blob/c0f6fb8f5d20d5404e51f12d9337c4284cf397a7/src/components/Item.tsx#L77) .

**Comment by evansjohnson** [comment]
Awesome, thanks for pointing that out, up to you if you think this use case is general enough to support here - ill probably just throw an extra prop for that in on my fork for now.

**Comment by fkhadra** [comment]
Possible in v5. Documented [here](https://fkhadra.github.io/react-contexify/prevent-menu-from-closing)
