### ISSUE TITLE
onHide and onShow events for Menu

### ISSUE THREAD

**Issue by tewk** [fkhadra/react-contexify#95]
Background:
I have a custom modal editor that uses a window scope keyboard event handler.

Feature request:
I want to remove the window scope keyboard event handler when a context menu is shown, and reinstate the window scope keyboard handler when the context menu hides.

I believe if onShow and onHide props where implemented this would be possible.

**Comment by hb-bobo** [comment]
onShow：You can use ContextMenu.show;


`contextMenu.show({
      id: 'menu_id',
      event: e,
      props: {
        msg: 'hello'
      }
    });`
